name=SmartHome
version=1.0.0
author=Sangram Nerkar
maintainer=Sangram Nerkar
sentence=Strict Dual-Core Home Automation with Gemini AI
paragraph=A crash-free ESP32 automation system with web server and hardware separation.
category=Control
url=https://github.com/Sangram141220/ESP32-Smart-Hub
architectures=esp32

