    - name: Install ESP32 Core and Libraries
      run: |
        arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core install esp32:esp32@2.0.17 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli lib install "ArduinoJson"
        
        # जुने व्हर्जन (३.०.६) वापरणे जे २.०.१७ सोबत चालते
        mkdir -p /home/runner/Arduino/libraries
        cd /home/runner/Arduino/libraries
        wget https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/3.0.6.zip
        unzip 3.0.6.zip
        mv ESP32-audioI2S-3.0.6 ESP32-audioI2S
        
