name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.0

      - name: Install Libraries
        run: |
          arduino-cli lib install ArduinoJson
          git clone --depth=1 https://github.com/schreibfaul1/ESP32-audioI2S.git ~/Arduino/libraries/ESP32-audioI2S

      - name: Compile Firmware
        run: |
          mkdir -p build

          arduino-cli compile \
            --fqbn esp32:esp32:esp32:PartitionScheme=huge_app \
            --build-property build.flash_size=4MB \
            --build-property upload.maximum_size=3145728 \
            --output-dir build \
            --export-binaries \
            .

      - name: Show Files
        run: ls -lh build

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-Smart-Hub-Firmware
          path: build/*.bin
